version: '3.5'
services:
  ###
  # services
  ###
    django-app:
        build: .
        # command: python manage.py runserver 0.0.0.0:8000
        container_name: django_server
        environment: 
            - SECRET_KEY=sigma274ing@dwEtRusT#
        volumes:
            - static:/static
            - appdata:/db
        ports:
            - "8000:8000"
        depends_on:
            - scrapyd-service
        networks:
            - backend
    scrapyd-service:
        build:
            context: app
            dockerfile: ./Dockerfile
        # dockerfile: ./scrapy_app/Dockerfile
        container_name: scrapyd_server
        volumes: 
            - appdata:/db
        ports:
            - "6800:6800"
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.8"
                    memory: 1500M
                # reservations:
                #     cpus: "0.7"
                #     memory: 1000M
    nginx:
        build: app/nginx
        volumes: 
            - static:/static
        ports: 
            - "80:80"
        depends_on:
            - django-app
        networks: 
            - backend 
networks:
    backend:
        driver: bridge
volumes: 
    static:
    appdata: