# Generated by Django 2.0.12 on 2021-05-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField()),
                ('brand', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
